export const products = [
    {
        id: 1, 
        name: 'Crisp Upland Kangkong',
        description: 'Freshly harvested water spinach, perfect for sinigang or adobo.',
        price: 80.00,
        from: 'Baguio City, Benguet',
        image: '🥬',
        rating: 5,
    },
    { 
        id: 2,
        name: 'Free-Range Eggs (1 Dozen)',
        description: 'Fresh, local free-range eggs with rich, golden yolks.',
        price: 120.00,
        from: 'Tarlac',
        image: '🥚',
        rating: 5,
    },
    {
        id: 3,
        name: 'Organic Highland Carrots',
        description: 'Bright orange and full of flavor. No pesticides, just pure goodness.',
        price: 120.00,
        from: 'Benguet Farms',
        image: '🥕',
        rating: 4,
    },
    {
        id: 4,
        name: 'Fresh Strawberries (1/2 Kilo)',
        description: 'Plump and juicy strawberries, picked daily from La Trinidad.',
        price: 350.00,
        from: 'La Trinidad, Benguet',
        image: '🍓',
        rating: 5,
    },
    {
        id: 5,
        name: 'Native Tomatoes',
        description: 'Locally grown tomatoes, perfect for salads, salsas, and sauces.',
        price: 90.00,
        from: 'Nueva Ecija',
        image: '🍅',
        rating: 4,
    },
    {
        id: 6,
        name: 'Ripe Saba Bananas',
        description: 'Versatile saba bananas, ideal for turon, bananacue, or nilaga.',
        price: 130.00,
        from: 'Davao',
        image: '🍌',
        rating: 5,
    },
];